/**:
    ros__parameters:
      registration_method: "NDT_OMP"
      score_threshold: 2.0
      ndt_resolution: 1.0
      ndt_step_size: 0.1
      ndt_num_threads: 4
      ndt_max_iterations: 35
      transform_epsilon: 0.01
      voxel_leaf_size: 0.2
      scan_max_range: 10.0
      scan_min_range: 0.5
      scan_period: 0.1
      use_pcd_map: true
      map_path: "/home/tekes/Documents/saha_staj/veli_unlu_pkg/src/lidar_localization_ros2/pcd_datas/result.pcd"
      set_initial_pose: true
      initial_pose_x: 5.0
      initial_pose_y: -5.0
      initial_pose_z: 0.0
      initial_pose_qx: 0.0
      initial_pose_qy: 0.0
      initial_pose_qz: 0.0
      initial_pose_qw: 0.0
      use_odom: false
      use_imu: true
      enable_debug: true
      global_frame_id: map
      odom_frame_id: odom
      base_frame_id: base_link
      threshold_x: 0.15
      threshold_y: 0.15
      threshold_z: 0.15
      threshold_roll: 0.5
      threshold_pitch: 0.5
      threshold_yaw: 0.5

